--Generated by proto-gen-lua Do not edit
local this= {}

this.DATA_BUFFS = "Data_Buffs"
this.DATA_SKILLOBJ = "Data_SkillObj"
this.DATA_USERACTIVITY = "Data_UserActivity"
this.DATA_USERACTIVITYNODE = "Data_UserActivityNode"
this.DATA_USERBAGITEM = "Data_UserBagItem"
this.DATA_CURRENCIES = "Data_Currencies"
this.DATA_USEREXP = "Data_UserExp"
this.DATA_USERHERO = "Data_UserHero"
this.DATA_USERQUEST = "Data_UserQuest"
this.DATA_USERQUESTREWARD = "Data_UserQuestReward"
this.DATA_SCENEOBJ = "Data_SceneObj"
this.DATA_BULLET = "Data_Bullet"

return this
